### PR TITLE
feat: login UI and some refactors 

### PR DESCRIPTION
**Pull request by abhimishra01**
### Task Link

---
- https://www.notion.so/FE-Login-Container-UI-4de088c102e44c6f84851088d3d65f6a?pvs=4
---

### Description

---
- update the login screen with the UI identical to `Signup` UI
- some refactors around previous code implementations
- add `/login` route redirection in `Signup` screen and vice versa for `Login` screen
- also removed the `loading...` text from signup button at the time of loading along with making it disabled during the same state which is not needed, the `loading` prop is enough to show loading state with a `spinner` 
---

### Screenshot / Gif (If Any)

---
- login

---

### TODO Checklist

- [x] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added]
- [ ] Relevant documentation is changed or added (and PR referenced)

### CODE REVIEW

**Review by BhanuPratap-Singh-Naruka — CHANGES_REQUESTED** [review]
Please make some change in styling of footer there should be some gap between body and footer

**Comment by abhimishra01** [comment]
> Please make some change in styling of footer there should be some gap between body and footer
Screenshot 2023-03-23 at 10 05 32 AM

will this gap work?

**Review by BhanuPratap-Singh-Naruka — COMMENTED** [review]
We also should add some padding-y inside the footer

**Comment by abhimishra01** [comment]
> We also should add some padding-y inside the footer
this should work
Screenshot 2023-03-23 at 11 07 59 AM


Screenshot 2023-03-23 at 11 08 07 AM

**Review by BhanuPratap-Singh-Naruka — APPROVED** [review]

**Pull request merged**
